jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: ./.github/actions/docker_build
        with:
          image_name: academy
          tag_name: v1.0.0

      - name: Push Docker image
        uses: ./.github/actions/docker_push
        with:
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          image_reference: academy:v1.0.0
